// Code generated by burrow build (Go target) -- VS0-for-Go v0, DO NOT EDIT.

package burrowgen

type Result struct {
	Tag   int // 1 = Ok, 0 = Err
	Value any
}

type Option struct {
	Tag   int // 1 = Some, 0 = None
	Value any
}

func InterpretHealthResponse(status_code int32, body_ok bool) Result {
	return func() any {
		if !(status_code == 200) {
			return Result(Result{Tag: 0, Value: "unexpected HTTP status (real endpoint responded, but not with 200)"})
		}
		return Result(func() any {
			if !(body_ok) {
				return Result(Result{Tag: 0, Value: "endpoint responded 200 but its own body reported not-ok"})
			}
			return Result(Result{Tag: 1, Value: "IDUNA_PRO instance is healthy"})
		}().(Result))
	}().(Result)
}

func ExitCodeForHealth(status_code int32, body_ok bool) int32 {
	return func() any {
		__match_tmp_1 := InterpretHealthResponse(status_code, body_ok)
		if __match_tmp_1.Tag == 1 {
			message := __match_tmp_1.Value.(string)
			_ = message
			return int32(0)
		} else {
			message := __match_tmp_1.Value.(string)
			_ = message
			return int32(1)
		}
	}().(int32)
}
