// Code generated by burrow build (Go target) -- VS0-for-Go v0, DO NOT EDIT.

package burrowgen

type Result struct {
	Tag   int // 1 = Ok, 0 = Err
	Value any
}

type Option struct {
	Tag   int // 1 = Some, 0 = None
	Value any
}

type HealthStatus struct {
	Tag   int
	Value any
}

func HealthStatus_Healthy() HealthStatus {
	return HealthStatus{Tag: 0}
}

func HealthStatus_BadStatus() HealthStatus {
	return HealthStatus{Tag: 1}
}

func HealthStatus_NotOk() HealthStatus {
	return HealthStatus{Tag: 2}
}

func ClassifyHealth(status_code int32, body_ok bool) HealthStatus {
	return func() any {
		if !(status_code == 200) {
			return HealthStatus(HealthStatus_BadStatus())
		}
		return HealthStatus(func() any {
			if !(body_ok) {
				return HealthStatus(HealthStatus_NotOk())
			}
			return HealthStatus(HealthStatus_Healthy())
		}().(HealthStatus))
	}().(HealthStatus)
}

func HealthMessage(status_code int32, body_ok bool) string {
	return func() any {
		__match_tmp_1 := ClassifyHealth(status_code, body_ok)
		if __match_tmp_1.Tag == 0 {
			return string("IDUNA_PRO instance is healthy")
		} else if __match_tmp_1.Tag == 1 {
			return string("unexpected HTTP status (real endpoint responded, but not with 200)")
		} else {
			return string("endpoint responded 200 but its own body reported not-ok")
		}
	}().(string)
}

func HealthExitCode(status_code int32, body_ok bool) int32 {
	return func() any {
		__match_tmp_2 := ClassifyHealth(status_code, body_ok)
		if __match_tmp_2.Tag == 0 {
			return int32(0)
		} else if __match_tmp_2.Tag == 1 {
			return int32(1)
		} else {
			return int32(1)
		}
	}().(int32)
}
