package auth

import "time"

// AppleRecord is a golden documentation entry from a self-improvement run.
// Append-only: records are never updated or deleted.
type AppleRecord struct {
	ID         int64
	AgentID    string
	SourceRepo string
	RunID      string
	AppleType  string
	Title      string
	Body       string
	Metadata   []byte    // raw JSON, may be nil
	RecordedAt time.Time
}

// CameraObservation is an image submitted by MJOLNIR for Emily Prime vision analysis.
type CameraObservation struct {
	ID          int64
	AgentName   string
	ImageData   string // base64-encoded
	MediaType   string // "image/jpeg" | "image/png" | "image/webp"
	Prompt      string // optional user context
	Analysis    string // filled by Emily Prime
	AppleID     int64  // IDUNA Apple filing the analysis
	Status      string // pending | processing | done | error
	CreatedAt   time.Time
	ProcessedAt *time.Time
}

// PushToken is an FCM device token registered by a MJOLNIR Android client.
// Upserted on each app launch; agent_name identifies the device owner.
type PushToken struct {
	ID          int64
	AgentName   string
	Platform    string // "android"
	FCMToken    string
	Fingerprint string
	RegisteredAt time.Time
	LastUsedAt   time.Time
}

// Agent is a first-class IAM identity for automated systems.
type Agent struct {
	ID          string
	OwnerUserID string
	Name        string
	Type        string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Permissions []string
	// HasCredential is true once SetAgentCredential has been called at least
	// once (api_key_hash is non-empty). Populated by ListAgents for the Back
	// Office console; not persisted on the struct itself.
	HasCredential bool
}

// ClusterHeartbeat tracks the live state of a federated Emily cluster.
// Upserted every 60 s by emily-agent on startup and each cron cycle.
type ClusterHeartbeat struct {
	AgentID      string
	ClusterID    string
	Capabilities []string  // e.g. ["gpu", "secwatch", "prwatch"]
	LoadScore    float64   // 0.0=idle → 1.0=saturated
	LastSeen     time.Time
}

// Role is a named set of permissions in the RBAC system.
type Role struct {
	ID          string
	Name        string
	Description string
}

// SprintItem is a HEIMDAL sprint planning record — a human product requirement
// translated by Emily Prime into an RSI roadmap item with acceptance criteria.
type SprintItem struct {
	ID           int64
	AgentName    string
	Requirement  string    // raw human product requirement text
	CriteriaJSON string    // JSON array of AcceptanceCriterion generated by Emily Prime
	RoadmapID    string    // populated once Emily queues the roadmap item
	Status       string    // pending | queued | in_progress | complete | blocked
	AppleID      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// IAMEvent is a record from the iam_event_stream audit log.
type IAMEvent struct {
	EventID       int64
	EventType     string
	AggregateType string
	AggregateID   string
	OperatorID    string
	Payload       []byte
	RecordedAt    time.Time
}
